In [109]:
import pandas as pd

In [110]:
data = pd.read_csv('Loan_default_kaggle.csv')

In [111]:
data

LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0       I38PQUQS96   56   85994       50587          520              80   
1       HPSK72WA7R   69   50432      124440          458              15   
2       C1OZ6DPJ8Y   46   84208      129188          451              26   
3       V2KKSFM3UN   32   31713       44799          743               0   
4       EY08JDHTZP   60   20437        9139          633               8   
...            ...  ...     ...         ...          ...             ...   
255342  8C6S86ESGC   19   37979      210682          541             109   
255343  98R4KDHNND   32   51953      189899          511              14   
255344  XQK1UUUNGP   56   84820      208294          597              70   
255345  JAO28CPL4H   42   85109       60575          809              40   
255346  ZTH91CGL0B   62   22418       18481          636             113   

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0                    4         15.23        36      0.44   Bachelor's   
1                    1          4.81        60      0.68     Master's   
2                    3         21.17        24      0.31     Master's   
3                    3          7.07        24      0.23  High School   
4                    4          6.51        48      0.73   Bachelor's   
...                ...           ...       ...       ...          ...   
255342               4         14.11        12      0.85   Bachelor's   
255343               2         11.55        24      0.21  High School   
255344               3          5.29        60      0.50  High School   
255345               1         20.90        48      0.44  High School   
255346               2          6.73        12      0.48   Bachelor's   

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0           Full-time      Divorced         Yes           Yes       Other   
1           Full-time       Married          No            No       Other   
2          Unemployed      Divorced         Yes           Yes        Auto   
3           Full-time       Married          No            No    Business   
4          Unemployed      Divorced          No           Yes        Auto   
...               ...           ...         ...           ...         ...   
255342      Full-time       Married          No            No       Other   
255343      Part-time      Divorced          No            No        Home   
255344  Self-employed       Married         Yes           Yes        Auto   
255345      Part-time        Single         Yes           Yes       Other   
255346     Unemployed      Divorced         Yes            No   Education   

       HasCoSigner  Default  
0              Yes        0  
1              Yes        0  
2               No        1  
3               No        0  
4               No        0  
...            ...      ...  
255342          No        0  
255343          No        1  
255344         Yes        0  
255345          No        0  
255346         Yes        0  

[255347 rows x 18 columns]

In [112]:
df1 = data[:1000]
df1

LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0    I38PQUQS96   56   85994       50587          520              80   
1    HPSK72WA7R   69   50432      124440          458              15   
2    C1OZ6DPJ8Y   46   84208      129188          451              26   
3    V2KKSFM3UN   32   31713       44799          743               0   
4    EY08JDHTZP   60   20437        9139          633               8   
..          ...  ...     ...         ...          ...             ...   
995  31SJTMWFCT   60   87805      124827          842              30   
996  R738Q1I3JW   64  129745      214172          843             105   
997  2A7OI5RIMX   62   58712      188494          700              62   
998  HUO1LPG2Q3   35  108703       44268          604              98   
999  04ZFSPHW91   55  146660      223015          737              56   

     NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0                 4         15.23        36      0.44   Bachelor's   
1                 1          4.81        60      0.68     Master's   
2                 3         21.17        24      0.31     Master's   
3                 3          7.07        24      0.23  High School   
4                 4          6.51        48      0.73   Bachelor's   
..              ...           ...       ...       ...          ...   
995               4          9.11        36      0.66     Master's   
996               1          9.00        60      0.59     Master's   
997               1         10.62        24      0.78   Bachelor's   
998               2          3.94        36      0.36     Master's   
999               1          7.67        60      0.61   Bachelor's   

    EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0        Full-time      Divorced         Yes           Yes       Other   
1        Full-time       Married          No            No       Other   
2       Unemployed      Divorced         Yes           Yes        Auto   
3        Full-time       Married          No            No    Business   
4       Unemployed      Divorced          No           Yes        Auto   
..             ...           ...         ...           ...         ...   
995      Part-time      Divorced         Yes           Yes    Business   
996     Unemployed       Married         Yes           Yes        Home   
997     Unemployed      Divorced         Yes           Yes        Home   
998     Unemployed        Single         Yes            No    Business   
999     Unemployed       Married          No            No   Education   

    HasCoSigner  Default  
0           Yes        0  
1           Yes        0  
2            No        1  
3            No        0  
4            No        0  
..          ...      ...  
995          No        0  
996         Yes        0  
997         Yes        0  
998          No        0  
999         Yes        0  

[1000 rows x 18 columns]

In [113]:
df2 = df1[['Age','Income','LoanAmount','CreditScore','LoanTerm', 'EmploymentType','MaritalStatus', 'Default']]
df2.head(50)

Age  Income  LoanAmount  CreditScore  LoanTerm EmploymentType  \
0    56   85994       50587          520        36      Full-time   
1    69   50432      124440          458        60      Full-time   
2    46   84208      129188          451        24     Unemployed   
3    32   31713       44799          743        24      Full-time   
4    60   20437        9139          633        48     Unemployed   
5    25   90298       90448          720        24     Unemployed   
6    38  111188      177025          429        12     Unemployed   
7    56  126802      155511          531        60      Full-time   
8    36   42053       92357          827        48  Self-employed   
9    40  132784      228510          480        48  Self-employed   
10   28  140466      163781          652        48     Unemployed   
11   28  149227      139759          375        36      Full-time   
12   41   23265       63527          829        60      Full-time   
13   53  117550       95744          395        24     Unemployed   
14   57  139699       88143          635        48      Part-time   
15   41   74064      230883          432        60     Unemployed   
16   20  119704       25697          313        24     Unemployed   
17   39   33015       10889          811        60  Self-employed   
18   19   40718       78515          319        24  Self-employed   
19   41  123419      161146          376        60  Self-employed   
20   61   30142      133714          429        12      Part-time   
21   47  146113      100621          419        12     Unemployed   
22   55  132058      130912          583        60     Unemployed   
23   19  118989      123300          528        36      Part-time   
24   38   56848      168918          468        24     Unemployed   
25   50   81649       78193          839        48      Part-time   
26   29  114651      197648          343        24      Part-time   
27   39   17633      167105          514        36      Full-time   
28   61   62519       29676          462        48     Unemployed   
29   42  141412      197764          580        12      Full-time   
30   66   39568       58945          604        12     Unemployed   
31   44  100284      225403          551        36     Unemployed   
32   59  102292       55337          840        60     Unemployed   
33   45   85673       48773          787        24      Full-time   
34   33   92448       66282          607        12      Part-time   
35   32  102178      179279          669        12  Self-employed   
36   64  102463      218433          506        60     Unemployed   
37   68   85409       44772          540        36     Unemployed   
38   61   26470       19818          695        36     Unemployed   
39   69   87295       16281          707        60      Part-time   
40   20  139321       43049          458        36  Self-employed   
41   54   21487       84115          386        60     Unemployed   
42   68  111716      215851          747        60     Unemployed   
43   24  105732       33013          400        36      Full-time   
44   38   73117      221628          639        36      Part-time   
45   26  125268       67671          795        12  Self-employed   
46   56   24796       37657          498        48      Part-time   
47   35   95963       77552          560        24  Self-employed   
48   21   16170       66883          505        48  Self-employed   
49   42  143244      240591          393        36  Self-employed   

   MaritalStatus  Default  
0       Divorced        0  
1        Married        0  
2       Divorced        1  
3        Married        0  
4       Divorced        0  
5         Single        1  
6         Single        0  
7        Married        0  
8       Divorced        1  
9        Married        0  
10       Married        0  
11      Divorced        1  
12      Divorced        0  
13        Single        0  
14      Divorced        0  
15       Married        0  
16      

In [106]:
df2.Age.unique()

array([56, 69, 46, 32, 60, 25, 38, 36, 40, 28, 41, 53, 57, 20, 39, 19, 61,
       47, 55, 50, 29, 42, 66, 44, 59, 45, 33, 64, 68, 54, 24, 26, 35, 21,
       31, 67, 43, 37, 52, 34, 23, 51, 27, 48, 65, 62, 58, 18, 22, 30, 49,
       63])

In [67]:
df2.Income.unique()

array([ 85994,  50432,  84208,  31713,  20437,  90298, 111188, 126802,
        42053, 132784, 140466, 149227,  23265, 117550, 139699,  74064,
       119704,  33015,  40718, 123419,  30142, 146113, 132058, 118989,
        56848,  81649, 114651,  17633,  62519, 141412,  39568, 100284,
       102292,  85673,  92448, 102178, 102463,  85409,  26470,  87295,
       139321,  21487, 111716, 105732,  73117, 125268,  24796,  95963,
        16170, 143244, 103515, 100949,  92153,  70113,  24611,  37173,
        31137,  49565,  31644,  49113,  85814, 110606,  76136,  82461,
        37082, 149401,  77135,  34830, 142860,  20236,  17142,  60000,
       142986,  59079, 118725, 130625,  49191,  46887,  23574,  49335,
       143837,  99977,  80770,  46238,  24742,  56982, 137937, 109000,
        59243,  35815, 138569,  90042,  93741, 114694, 108283,  30200,
        25274,  55299, 100459,  74554,  47383, 148123, 128414,  40782,
        28436, 145047,  93993, 137295,  29782,  39811,  42063,  21711,
      

In [77]:
df2.CreditScore.min()

np.int64(300)

In [71]:
print(df2.columns.tolist())


['Age', 'Income', 'LoanAmount', 'CreditScore', 'LoanTerm', 'EmploymentType', 'MaritalStatus', 'EmploymentType', 'Default']


In [74]:
df2.columns = df2.columns.str.strip()


In [84]:
df2.LoanTerm.unique()

array([36, 60, 24, 48, 12])

In [98]:
df2["MaritalStatus"].unique()

array(['Divorced', 'Married', 'Single'], dtype=object)

In [121]:
df2.MaritalStatus.unique()

array([0, 1, 2])

In [118]:
from sklearn.preprocessing import LabelEncoder

# Create the encoder
le = LabelEncoder()

# Apply to the column
df2['MaritalStatus'] = le.fit_transform(df2['MaritalStatus'])
df2['EmploymentType'] = le.fit_transform(df2['EmploymentType'])

C:\Users\sowmi\AppData\Local\Temp\ipykernel_432\2596458453.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['MaritalStatus'] = le.fit_transform(df2['MaritalStatus'])
C:\Users\sowmi\AppData\Local\Temp\ipykernel_432\2596458453.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['EmploymentType'] = le.fit_transform(df2['EmploymentType'])


In [114]:
df2.EmploymentType.unique()

array(['Full-time', 'Unemployed', 'Self-employed', 'Part-time'],
      dtype=object)

In [119]:
df2.EmploymentType.unique()

array([0, 3, 2, 1])

In [122]:
df2.head()

Age  Income  LoanAmount  CreditScore  LoanTerm  EmploymentType  \
0   56   85994       50587          520        36               0   
1   69   50432      124440          458        60               0   
2   46   84208      129188          451        24               3   
3   32   31713       44799          743        24               0   
4   60   20437        9139          633        48               3   

   MaritalStatus  Default  
0              0        0  
1              1        0  
2              0        1  
3              1        0  
4              0        0